
-- Insert 50 preset quests into quests table
INSERT INTO quests (name, emoji, description, type, xp_value, is_custom, created_at, updated_at) VALUES
  ('Send a thank you note', '✉️', 'Write and send a thank you note to someone.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Take a 10-minute walk', '🚶‍♂️', 'Enjoy a short walk to refresh your mind.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Read a chapter of a book', '📖', 'Spend time reading to expand your knowledge.', 'weekly', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Call a family member', '📞', 'Reach out and check in with a family member.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Meditate for 5 minutes', '🧘‍♀️', 'Practice mindfulness meditation.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Cook a healthy meal', '🍳', 'Prepare a nutritious meal from scratch.', 'weekly', 30, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Clean your workspace', '🧹', 'Organize and tidy your work area.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Compliment a stranger', '😊', 'Give a genuine compliment to someone.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Plant a flower or tree', '🌱', 'Contribute to nature by planting.', 'weekly', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Write down 3 things you are grateful for', '📝', 'Reflect on positive aspects of your life.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Drink 8 glasses of water', '💧', 'Stay hydrated throughout the day.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Practice a new skill for 30 minutes', '🎨', 'Dedicate time to learning something new.', 'weekly', 30, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Declutter a drawer or shelf', '🗄️', 'Remove unnecessary items and organize.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Send a positive message to a friend', '💌', 'Reach out with kind words.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Try a new recipe', '🍲', 'Cook something you have never tried before.', 'weekly', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Take 10 deep breaths', '🌬️', 'Practice deep breathing for relaxation.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Write a journal entry', '📓', 'Reflect on your day or thoughts.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Donate unused items', '🎁', 'Give away items you no longer need.', 'weekly', 30, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Compliment your pet', '🐾', 'Show love and appreciation to your pet.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Stretch for 10 minutes', '🤸‍♂️', 'Improve flexibility and reduce tension.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Listen to your favorite song', '🎵', 'Enjoy music that lifts your mood.', 'weekly', 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Write a poem or short story', '✍️', 'Express creativity through writing.', 'weekly', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Spend time outside', '🌞', 'Enjoy fresh air and nature.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Organize your email inbox', '📧', 'Clear clutter and organize emails.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Try a new workout', '🏋️‍♀️', 'Challenge your body with something new.', 'weekly', 30, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Watch an educational video', '🎥', 'Learn something new via video.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Make your bed', '🛏️', 'Start the day with a tidy bed.', 'weekly', 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Smile at 5 people', '😁', 'Spread positivity with smiles.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Write a thank you email', '📩', 'Express gratitude professionally.', 'weekly', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Try a new hobby', '🎯', 'Explore a new interest or activity.', 'weekly', 30, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Read a news article', '📰', 'Stay informed about current events.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Practice a language for 15 minutes', '🗣️', 'Improve language skills.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Write a list of goals', '🎯', 'Plan your week with clear objectives.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Take a photo of something beautiful', '📷', 'Capture moments of beauty.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Help someone with a task', '🤝', 'Offer assistance to others.', 'weekly', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Try a new tea or coffee', '☕', 'Enjoy a new beverage.', 'weekly', 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Write a positive affirmation', '💬', 'Boost your confidence.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Organize your bookshelf', '📚', 'Arrange your books neatly.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Spend 10 minutes stretching', '🧘', 'Relax your muscles.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Plan a weekend activity', '📅', 'Prepare for fun and relaxation.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Write a letter to your future self', '✉️', 'Reflect and set intentions.', 'weekly', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Try a new fruit or vegetable', '🍎', 'Expand your diet.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Do a random act of kindness', '❤️', 'Make someone’s day better.', 'weekly', 30, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Unplug from devices for 1 hour', '📵', 'Take a digital detox.', 'weekly', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Write a gratitude letter', '📝', 'Express thanks to someone.', 'weekly', 25, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Try a breathing exercise', '🌬️', 'Calm your mind.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Organize your wallet or purse', '👛', 'Clear out unnecessary items.', 'weekly', 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Make a healthy snack', '🥗', 'Prepare nutritious food.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Write down your favorite memories', '📔', 'Recall joyful moments.', 'weekly', 20, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Try a new podcast episode', '🎧', 'Learn or be entertained.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('Give yourself a compliment', '🌟', 'Boost your self-esteem.', 'weekly', 15, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
